### ISSUE TITLE
Change Name of modifier to visibility 

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Famix#103]
A visibility refers only to public, private, protected and so on.
Since each entity will have only one modifier, and not a collection, the way to access it should be changed (no more modifiers include:#toto).
Obviously, methods using modifier may eventually be modified consequently.

linked with moosetechnology/Moose#2098, moosetechnology/Moose#2121, moosetechnology/Moose#2202 and moosetechnology/Moose#2219.

**Comment by ClotildeToullec** [comment]
Fixed by https://github.com/moosetechnology/Famix/pull/195
