### ISSUE TITLE
Generator could export relations in comment

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#126]
It could be cool if the generator could export the list of possible parents/children/associations in the class comment of entities.

**Comment by NicolasAnquetil** [comment]
We can now generate a UML diagram from a MM.
I think that would answer to the need no ?

**Comment by jecisc** [comment]
I think it would be nice to have it in the comment because it's not hard to do and when we code it would be the easiest way to have the infos. 

@Gabriel-Darbord said he might be interested to take a look at that

**Comment by NicolasAnquetil** [comment]
And we might as well also put the properties in this case
