### ISSUE TITLE
FAMIXAccess isRead/isWrite are both <derived>

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#161]
In the last version of FAMIX, isWrite was not `<derived>`.
Is it normal that now it is derived?

If yes, how should VerveineJ export the value? (by default, derived should not be derived, so now, from VerveineJ we should not export isWrite? )

**Comment by NicolasAnquetil** [comment]
Yes, this is strange.
We should revert to the old behaviour: assume Acceses are not write-access by default and export isWrite=true when needed.
