### ISSUE TITLE
numberOfStatements is now derived

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#162]
Does that mean VerveineJ does not need to export this value?

**Comment by NicolasAnquetil** [comment]
no, it needs to export the info because it cannot be recomputed from what we have in Famix.

**Comment by jecisc** [comment]
Then the property should not be derived in the famix java model or the data will be lost

**Comment by badetitou** [comment]
I think like Cyril, we should then make it "not derived" in the famix java meta-model
