### ISSUE TITLE
namedEntity in JavaBuilder has no 'name' slot

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#163]
This is the definition of `namedEntity` in `FamixJavaGenerator` :
```st
	namedEntity --|> #TPackageable.
	namedEntity --|> #TInvocationsReceiver.
	namedEntity --|> #TWithAnnotationInstances.
	namedEntity --|> #THasModifiers.
```
So all entities in the model (classes, methods, packages, variables, ... get their name slot from somewhere else.

-> rename this instance variable so that it is not misleading

**Comment by anneetien** [comment]
The name is well defined in namedEntity but in FamixBasicInfrastructureGenerator, from where FamixJavaGenerator inherits.
New traits are added in FamixJavaGenerator.
