### ISSUE TITLE
What is the point of overriding the method FamixJavaType>>isAbstract

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#184]
The method only call super.
Is it to change the comment? (might be a good reason)

**Comment by ClotildeToullec** [comment]
Plus: there is no #isAbstract in superclasses. So this is always a DNU.
This looks like we should remove it.

FamixJavaClass uses TCanBeAbstract, I am not sure any other subclass of JavaType should?

**Comment by ClotildeToullec** [comment]
Todo: remove #isAbstract from FamixJavaClass
