### ISSUE TITLE
In Java Annotations need to be TWithInheritance ...

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#187]
... because they can be _implemented_ by regular classes

**Comment by anneetien** [comment]
Is it really inheritance? 
Do we need to add a new type of relations?

Anne

**Comment by NicolasAnquetil** [comment]
It seems it is a "normal" inheritance: [https://stackoverflow.com/questions/3341930/use-cases-for-implementing-annotations](https://stackoverflow.com/questions/3341930/use-cases-for-implementing-annotations)

**Comment by ClotildeToullec** [comment]
Fixed by #221
