### ISSUE TITLE
revisit (rename?) TWithException

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#196]
This is a strange trait with an unclear purpose (to me) : 
- `Class` uses this trait, but class cannot have exceptions, only methods can declare/throw/catch exceptions
- its getter `#exceptions` says: 'Exceptions which class is myself.'

It seems to be used to mark classes which are actually exceptions, but then the name is not correct because an Exception (a class which is an exception) does not have exceptions ...

**Comment by ClotildeToullec** [comment]
Todo: update implementation.

Situation now: 
- TWithExceptions is used by classes, to link a class to the exception that ***it actually is***.
- Relation slot between TWithExceptions and many TException, so 1 java exception is represented by 2 entities: the implementing class + the exception.

It should be: 
- an exception is a class (TException should use TClass).
- TWithExceptions should be removed, also should be the relation with TException.

Note that we keep TWithCaughtExceptions, TWithDeclaredException and TWithThrownException. They are used by Java Methods.

**Comment by anneetien** [comment]
An Exception can be thrown, caught, declared, or not, by methods.
According to me, it is not normal to have FamixJavaDeclaredException, FamixJavaCaughtException and so on. We should have FamixJavaException and the methods that declare, catch or throw it. So we can't have the three properties called definingEntity, but instead declaringEntity, catchingEntity and throwingEntity. 
By the way, it should be *-* relations between (tDeclaredException and tWithDeclaredExceptions) and resp the others.
FamixJavaMethod should use the three traits tWithDeclaredException (resp caught and thrown)...
So I propose to replace 
        (tDeclaredException property: #definingEntity))
		*-
	((tWithDeclaredExceptions property: #declaredExceptions)
by 
(tException property: #declaringEntity))
		*-*
	((tWithDeclaredExceptions property: #declaredExceptions) 
and so on.

And we can also consider that TException uses TClass.

What do you think about?
@badetitou @NicolasAnquetil

**Comment by NicolasAnquetil** [comment]
makes sense to me
We could remove:
- FamixJavaDeclaredException, FamixJavaCaughtException, FamixJavaThrownException
- FamixTDeclaredException, FamixTCaughtException, FamixTThrownException
and keep only TException and JavaException that would have 3 different slots to register where they are declared, caught and thrown
