### ISSUE TITLE
FAMIX specification comparison

### ISSUE THREAD

**Issue by Ennowulff** [moosetechnology/Famix#198]
Hey there!
I found specifications for FAMIX [2.1](https://www.researchgate.net/publication/243775208_FAMIX_2_1-the_FAMOOS_information_exchange_model) and [3.0](https://www.researchgate.net/publication/265428652_MSE_and_FAMIX_30_an_Interexchange_Format_and_Source_Code_Model_Family).

Is there any document where I can see the differences of those versions?

Background: Eventually I would like to adapt the [SAP2Moose extractor](https://github.com/SAP2Moose/SAP2Moose) by @RainerWinkler 

Thanks
Enno

**Comment by NicolasAnquetil** [comment]
Whao, this is super old. something like 10 years ago or so.

There was a small tool that did its best to convert automatically.
I think it was by Jannik Laval ?

We are now finishing the work on Famix-NG (eg [https://github.com/moosetechnology/moose-wiki/blob/master/Developers/CreateNewMetamodel.md](https://github.com/moosetechnology/moose-wiki/blob/master/Developers/CreateNewMetamodel.md) or Section 3 of [https://hal.inria.fr/hal-02972159v1](https://hal.inria.fr/hal-02972159v1)), so maybe it would be more sensible to migrate directly to this?
(depends on what you want to do after)

We can help you in this if needed

**Comment by Ennowulff** [comment]
Thanks for your fast reply @NicolasAnquetil !
If there was a AMIX converter tool, that would be great...! Didn't find something about it.

My intention is to try [CodeCity](http://wettel.github.io/codecity.html) with SAP sources. Code City requires FAMIX 2.1 format...
