### ISSUE TITLE
Back port CanBeClassSide to compatibilty MM

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#231]
Issue #213 introduced TCanBeClassSide in FamixJava
should be back ported to FAMIXCompatibility

**Comment by badetitou** [comment]
As described in PR #236.

You have only tested the case where isClassSide is set to true manually.
Then, what is the default value?

I expect:

```st
FAMIXClassTest >> testDefaultIsClassSide [
	| famixClass |
	famixClass := FamixJavaClass new. 
	self deny: famixClass isClassSide
]
```

Please consider adding a test and fix the behavior
