### ISSUE TITLE
TNamed and TNamedEntity are duplicates ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#238]
Why having 2 ?
-> keep only TNamedEntity ?

**Comment by badetitou** [comment]
One is deprecated.

**Comment by badetitou** [comment]
We should keep it for compatibility

**Comment by NicolasAnquetil** [comment]
OK, so FamixTNamed is deprecated.
That's a good start, but not everybody pay attention to that unfortunately.
And people might even use both in the same MM :-(
So it would be good to remove FAMIXTNamed
