### ISSUE TITLE
Remove FAMIXTNamed

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#239]
It is deprecated and a duplicate of FamixTNamedEntity (see #238)
Having both creates confusion

**Comment by badetitou** [comment]
If you use TNamed the generated are ~~crossed out~~. 
I personally used TNamed and now I use TNamedEntity. 

IMHO we **must** keep deprecated entity in the current state of the migration.

**Comment by badetitou** [comment]
For example, having the deprecated entity allowed us to delay the regeneration of FAST-Pharo to today (01/03/2021) -> https://github.com/moosetechnology/FAST-Pharo/pull/2

**Comment by anneetien** [comment]
FamixTNamed has been removed a long time ago.
@badetitou @NicolasAnquetil 
I suggest to close this issue.
