### ISSUE TITLE
What's the use of FamixTWithClassScope ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#240]
Trait is empty ...

**Comment by ClotildeToullec** [comment]
Empty, no users, no comment.
I vote for removing it.

**Comment by badetitou** [comment]
I have no clue what it is.
It has Traits users
![image](https://user-images.githubusercontent.com/6225039/111795903-ee21e400-88c7-11eb-875b-19ef542c658c.png)

I am for deprecation of the Trait in M9 -> to remove in M10
(If it does not create a problem with M9, let's do the thing correctly).
