### ISSUE TITLE
isAbstract should be put in separate trait

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#241]
TMethod and others define #isAbstract
would be better to have it in a separate trait to be able to reuse it easily

**Comment by anneetien** [comment]
It is already the case with TCanBeAbstract. What do you want more?

**Comment by ClotildeToullec** [comment]
I close this as, like Anne said, this was done with TCanBeAbstract.
@NicolasAnquetil don't hesitate to reopen if you don't agree.
