### ISSUE TITLE
FamixTNamedEntity should not use FamixTSourceEntity

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#242]
It seems to make sense in programming language context, but I think it is better to have bare simple traits rather than to try to be smart because in the long run, we are never quite smart enough and there is always an unforeseen scenario where it becomes a pain in the neck

**Comment by anneetien** [comment]
@NicolasAnquetil 
It seems it has been solved. What do you think?

**Comment by NicolasAnquetil** [comment]
yep
