### ISSUE TITLE
Remove FamixTWithMethods>>#numberOfMessageSends

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Famix#255]
It can only be computed in FamixStClass.
It should be #numberOutgoingInvocations, computed as:
```Smalltalk
self methodsGroup sumNumber: #numberOfOutgoingInvocations
```

**Comment by ClotildeToullec** [comment]
Also remove #numberOfMessageSends from TMethod and StMethod

**Comment by CafeKrem** [comment]
working on it
