### ISSUE TITLE
review #throughAll queries

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#27]
These queries only serve to get entities from queries instead of associations
#opposites can do the same

On the other hand, the new 'dependencySource'  mechanism (Moose issue 2092) implies that queries do not always return associations (for now we create fake associations, but it does not need to stay like that)

So we must think about what the queries should be and should return. May be it does not need to be always associations

**Comment by jecisc** [comment]
Not valid anymore since it is now part of the DSL and it does not duplicate the implementation anymore.

Queries can now return:
- Associations
- Objects (using `objects` in the DSL)
- Boolean (using `has` in the DSL)
