### ISSUE TITLE
Improve default name for MooseObject and MooseModel

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Famix#283]
```MooseObject>>#name``` returns #noname. Is this made to be overridden ?
```MooseModel>>#initialize``` does ```name := #noname```

There should *at least* be a class method in MooseObject, like ```undefinedName``` returning #noname.

**Comment by NicolasAnquetil** [comment]
or this could be a case of #228 ?

`mooseObject property: 'name' type: String defaultValue: #noname`

**Comment by ClotildeToullec** [comment]
I like that, yes

**Comment by lsafina** [comment]
fixed by creating undefinedName on MooseObject returning #noname.
