### ISSUE TITLE
rename Fame method FMMetaModel >> descriptionOf:

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#304]
The method actually allows to recover a FM3Type from its implementing class in Pharo
ex: from Pharo class `FamixJavaMethod` to FM3Class `Famix-Java-Entities.Method`

may be `fmTypeFor:` ?

**Comment by ClotildeToullec** [comment]
I agree and don't agree:
This is called from several methods: `#mooseDescriptionOf:` , `#asMooseDescription` , `metaDescriptionIn:`. All expect a 'description'. So it is consistent with its senders to keep 'description'.
Maybe it should be `metaDescriptionOf:`or `mooseMetaDescriptionOf:` ?

On the other hand, a moose meta description ***is*** a FMType, so why not `fmTypeFor:` indeed?

**Comment by badetitou** [comment]
I think, originally, `FM3Class` was named `FM3Description`
We can see it in the legacy code of FameJava
(https://github.com/moosetechnology/FameJava/blob/master/src/ch/akuhn/fame/fm3/MetaDescription.java)

Also, the keyword `Description` was used for more than the Type
- https://github.com/moosetechnology/FameJava/blob/master/src/ch/akuhn/fame/fm3/PackageDescription.java
- https://github.com/moosetechnology/FameJava/blob/master/src/ch/akuhn/fame/fm3/PropertyDescription.java

So, I think the `Description` keyword is ok.
But, maybe we should rename `descriptionOf:` as `metaDescriptionOf:` 
(I dislike `mooseDescriptionOf:`, what is Moose? Is it Fame? Is it Famix? Is it something else? I find it confusing)

As always, my main requirement is to have an automatic deprecation.

**Comment by jecisc** [comment]
A FM3Class is a description of an entity, so I guess it makes sense to keep it like this?
Maybe something to do would be to add the "Description" suffix to FMEntity's subclasses?

**Comment by ClotildeToullec** [comment]
Decided with @anneetien and @NicolasAnquetil : `description` is legacy and it's not clear that we expect a FM3Type.
So: deprecate `#descriptionOf:` and replace it with `fmTypeOf:`.

**Comment by anneetien** [comment]
This has been performed. descriptionOf: is deprecated in favor of fmTypeOf: (certainly since June 25, 2021 ;-))
