### ISSUE TITLE
FamixStClass>>sourceText is very slow

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#320]
It is using `TonelWriter sourceCodeOf: aClass`
Stephane suggested to use `aClass definitionString`

**Comment by anneetien** [comment]
I tried on a brand new image with a StModel with 18000 entities.
sourceText as currently defined is instantaneous. 
The suggestion proposed by Stéphane corresponds only to the class definition so what you get when you click on the class such as ```Model subclass: #LANNode
	instanceVariableNames: 'name nextNode'
	classVariableNames: ''
	poolDictionaries: 'LANPool'
	package: 'Moose-TestResources-LAN'```
Whereas the current definition gives the code of the class definition but also of all the methods.

So @NicolasAnquetil do you still have this issue? Or can we close it?
