### ISSUE TITLE
Remove FamixBasicInfrastructureGenerator

### ISSUE THREAD

**Issue by enwiro** [moosetechnology/Famix#330]
The FamixBasicInfrastructureGenerator is obsolete should be replace by importing subMetamodels and its classes / traits should be migrated to others generators (For example, FamixGenerator).

![image](https://user-images.githubusercontent.com/58632394/127637883-f3fc61cc-fe04-4168-86aa-12acc4b82e52.png)

**Comment by anneetien** [comment]
Do we still want to do that?

**Comment by NicolasAnquetil** [comment]
there is something to do with FamixBasicInfrastructureGenerator but it is not urgent and we are not sure what exactly
