### ISSUE TITLE
export privateState of entities ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#338]
When importing a model (from MSE or JSON), one can put extra properties in the description that are stored in the privateState of entities
For example, this could be used to store metrics on entities without having to change the MM

But on re-export (MSE or JSON) the privateState is not considered

Should we allow to export also privateState ?
Always ? or with an option ?

Note: export is actually handled by Fame, so if we decide to do it, it will need to be done there ...

**Comment by jecisc** [comment]
Hi,
The private state is an implementation detail. 

To know what to export or not, we need to consider the meta-model. 
- If a property stored via a private state is declared as derived: no export
- If a property stored via a private state is not declared as derived: it should export
- If something stored via a private state is not a property and it makes sense to export it, then it should be declared in the meta-model of the language

**Comment by Ducasse** [comment]
Yes cyril is totally right. 
Private state is like in Pharo where we have a property dict. the metamodel should tell us what to do for the export.

**Comment by lsafina** [comment]
closed as deprecated
