### ISSUE TITLE
`isPackage` is used for the visibility and the type testing

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#362]
The method `isPackage` is used for the visibility

```st
FamixTHasVisibility>>#isPackage
  <FMProperty: #isPackage type: #Boolean> <derived>
  <FMComment: 'Flag true for entities that have a package visibility. Language dependent.'>
    
  ^ self visibility = #package
```

and the type testing

```st
FamixTPackage>>#isPackage
  <generated>
  ^ true
```

Which lead to easy error.
We should rename the visibility in my opinion as 
- publicVisibility
- privateVisibility
- protectedVisibility
- packageVisibility

**Comment by anneetien** [comment]
Still not solved. We need to correct this bug

**Comment by anneetien** [comment]
close by #384
