### ISSUE TITLE
FamixTAttribute should not have #isClassSide property

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#37]
"Class side" is specific to Smalltalk but the property is present in FamixTAttribute. 

It should be removed from the generic trait and added to the specific generators. (probably Smalltalk and Compatibility)

**Comment by aranega** [comment]
It's not only Pharo specific no? In Python we have class variable (attribute class), method class and there is a kind of notion of class side also in Dart/Ruby.
We introduced a specific trait with PR #220 as answer to issues #203 #213

**Comment by ClotildeToullec** [comment]
For sprint, what's left to do:
- Delete TAttribute>>#isClassSide
- Remove TCanBeClassSide from TAttribute and add it to FamixStAttribute (and FAMIXAttribute).
Other MM generators (python or else) that need it should also add TCanBeClassSide to their Attribute

**Comment by anneetien** [comment]
We disagree with this proposal. It is just that static and class side are considered with the same trait. Do we need to differentiate them?
