### ISSUE TITLE
Initialization conflict for Traits and Classes with default value on properties

### ISSUE THREAD

**Issue by Croshiw** [moosetechnology/Famix#386]
When a Trait has a property with default value, an `initialize` method is generated to set the default value.
The same occurs in a class with default-valued property.

The issue is: when this class uses this trait, the `initialize` method of the trait is never called.

Proposed solution:
- Do not generate `initialize` in the traits as they can't be instantiated and to avoid conflict between traits.
- When generating the `initialize` in a class, get the properties of all its traits and set their default value if needed.

**Comment by Gabriel-Darbord** [comment]
See #557.
