### ISSUE TITLE
FamixTNamedEntity should bring only the name property

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Famix#408]
FamixTNamedEntity brings the name property but also uses FamixTSourcedEntity.

FamixJavaFile uses TNamedEntity and so is considered as SourcedEntity what is wrong.

PRoposed solution:
- remove from FamixTNamedEntity the usage of FamixTsourcedEntity.
- Add to the user of FamixTNamedEntity when useful the usage of FamixTSourcedEntity

**Comment by anneetien** [comment]
It seems this issue has been solved.
Agree?
@NicolasAnquetil @badetitou

**Comment by NicolasAnquetil** [comment]
yes solved (See also #242)
