### ISSUE TITLE
Create a separated project for FamixCpp

### ISSUE THREAD

**Issue by akevalion** [moosetechnology/Famix#414]
From this conversation:
https://github.com/moosetechnology/Famix/pull/413

Famix Baseline should be a core for future and separated projects for new famix meta models.

Then a new CppFamix meta model should be created for FamixCpp

**Comment by akevalion** [comment]
Current version of CppFamix is here https://github.com/akevalion/Famix-CPP

**Comment by NicolasAnquetil** [comment]
and the baseline should include PetitParser which is no longer in Moose by default

**Comment by akevalion** [comment]
Yes you can check that here https://github.com/akevalion/Famix-CPP/blob/master/src/BaselineOfFamixCpp/BaselineOfFamixCpp.class.st

**Comment by akevalion** [comment]
Last version is here! https://github.com/moosetechnology/Famix-Cpp
