### ISSUE TITLE
Cannot represent typed class hierarchy

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#428]
Considering the parametrizable class `Map<X,Y>`, we cannot fully represent the inheritance:

```java
class A extends Map<String, MyOtherObject> {
}
```

In the above example, the superclass of `A` is `Map<X,Y>` and we lose the information about `String` and `MyOtherObject`.

This case is originally reported by @greenpanther93.

We have to modify the metamodel to add such piece of information.

**Comment by NicolasAnquetil** [comment]
as I remember:
- Map should be a FamixJavaParameterizableClass
- A should be a FamixJavaParameterizedType (with #parameterizableClass = Map)
- X, Y, String, MyOtherObject are FamixJavaParameterType
