### ISSUE TITLE
Famix tagging: it should be possible to test if an entity is tagged with a given string

### ISSUE THREAD

**Issue by LABSARI** [moosetechnology/Famix#440]
There is the method isTaggedWith: that is awaiting a tag as parameter.
It should be nice to test it with a tag name (string).

**Comment by jecisc** [comment]
Might be nice to rename it #hasTag: with a deprecation transformation and add #hasTagNamed:

**Comment by anneetien** [comment]
Close with FamixTagging #11 and #12
