### ISSUE TITLE
How to represent ParametrizedInterface?

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#449]
Considering the following java piece of code:

```java
public interface MyInterface<T> {
}

public class MyClass implements MyInterface<String> {

}
```

We, today have the following entities:

- ParametrizableInterface  `MyInterface<T>`
- Class `MyClass`
- ParametrizedType `MyInterface<String>`

We can create the association:

- `MyClass` implements `MyInterface<T>`
or
- `MyClass` inherits from `MyInterface<String>`

But we _**cannot**_ represents 

- `MyClass` implements `MyInterface<String>`.

For Inheritances, the following pattern is used

- `MyClass` inheritFrom `MyOtherClass<String>`
- `MyOtherClass<String>` parametrizableClass `MyOtherClass<>`

### So, I see two options:

1. Create ParametrizedInterface, or
2. Enable ParametrizedType to be use as implementable

**Comment by NicolasAnquetil** [comment]
I did not follow. By "we cannot" you mean "we want but or not able to" or "we don't want to" ?
What does inheritance have to do with all this ? They are interfaces, so we want to use  "implements".

anyway it seems to me that
1. we need to create ParametrizedInterface
2. we might want ParametrizedType to be use as implementable

All this looks like trying to fit a multiple inheritance world into a single inheritance implementation. And the solution for this should be the traits ...

**Comment by anneetien** [comment]
@badetitou @NicolasAnquetil @LABSARI @ClotildeToullec still relevant?

**Comment by LABSARI** [comment]
We now have FamixJavaParametricInterface.
See PR #635 for more details.
