### ISSUE TITLE
TOODependencyQueries and TEntityMetaLevelDependency should be cleaned and merged.

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Famix#454]

**Comment by anneetien** [comment]
TOODependencyQueries defines 4 methods:
- TOODependencyQueries>>#queryStaticOutgoingAssociations.
- TOODependencyQueries>>#queryOutgoingInheritances.
- TOODependencyQueries>>#queryIncomingInheritances.
- TOODependencyQueries>>#queryStaticIncomingAssociations
Can we just deprecate TOODependencyQueries and remove usage of this trait?

**Comment by NicolasAnquetil** [comment]
TOODependencyQueries seems to override methods of TEntityMetaLevelDependency
wasn't it intended to create an OO-metamodel and a procedural-mm ?

**Comment by anneetien** [comment]
Fix by #473
