### ISSUE TITLE
TInterface does not use TCanImplement

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#480]
therefore an interface extending another interface must inherit from it

Although Java does use the word "extends" between sub-interface and super-interface(s), is that how we want to model it ?

**Comment by anneetien** [comment]
Interface uses TWithInheritances, because, it seems that between 2 interfaces, it is an Inheritance link, but between a class and an Interface, an Implements link.
Do you agree?

**Comment by NicolasAnquetil** [comment]
yes *Java* writes it "`extends`". The question is whether we want to consider it an inheritance or not ?

what is an inheritance in Famix and what is an implementation ?

**Comment by anneetien** [comment]
Implementation is between Interface and Class. Inheritance between types or concepts using TWithInheritances.
Anne

**Comment by NicolasAnquetil** [comment]
Summary, there are 3 different associations:
- from a class to super-classes -> inheritance
- from a class to implemented interfaces -> implements
- from an interface to super-interfaces -> ???
How do we call the last association?
Currently it is called inheritance, I was suggestion calling it implements, but neither solution is completely satisfying
We could introduce a new association: "subtypes" or "extends"

**Comment by badetitou** [comment]
Hello

IMO, we can keep `inheritance` between interfaces. I know it is not perfect, but it is more similar to what we can in the real code (with the `extend` keyword).

A `class` can implement an interface
A `type` can extends another type

```mermaid
classDiagram
    Type <|-- Interface 
    Type <|-- Class 
    Class "1" --> "*" Interface : implements
    Type "1" --> "0..1" Type : extends
```
