### ISSUE TITLE
remove TSourceEntity from sourcedEntity in FamixJavaGenerator ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#512]
`sourcedEntity --|> #TSourceEntity.` is already defined in FamixBasicInfrastructureGenerator, no need to repeat it in FamixJavaGenerator

**Comment by ClotildeToullec** [comment]
❓ It is not in FamixJavaGenerator.

**Comment by anneetien** [comment]
No more relevant
