### ISSUE TITLE
FamixJavaMethod #isGetter and #isSetter are inaccurate

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#520]
```st
isGetter

	^ self kind = #getter or: [   (self name beginsWith: 'get') and: [ 
		  self parameters isEmpty and: [ 
			  self accesses asOrderedCollection size = 1 and: [ 
				  self outgoingInvocations isEmpty ] ] ]]
```
```st
isSetter

	^ self kind = #setter or: [ (self name beginsWith: 'set') and: [ 
		  self parameters size = 1 and: [ 
			  self accesses asOrderedCollection size = 1 and: [ 
				  self outgoingInvocations isEmpty ] ] ] ]
```
Another common prefix for getters is `is`, mostly used with booleans.
Both methods have an issue with `self accesses asOrderedCollection size = 1` because the accessed attribute can be prefixed by a self access: `this.myAttribute`.
Also, using `asOrderedCollection` seems unnecessary since only the size matters.

**Comment by NicolasAnquetil** [comment]
ok for the 'is' prefix
ok for the useless asOrderedCollection

and if you can think of a better heuristics, its great

**Comment by Gabriel-Darbord** [comment]
Some heuristics taken from famous Java libraries:
[ByteBuddy](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/matcher/ElementMatchers.java)
```java
isGetter() {
  return takesNoArguments().and(not(returns(TypeDescription.ForLoadedType.of(void.class)))).and(nameStartsWith("get").or(nameStartsWith("is").and(returnsGeneric(anyOf(boolean.class, Boolean.class)))));
}
```
```java
isSetter() {
  return nameStartsWith("set").and(takesArguments(1)).and(returns(TypeDescription.ForLoadedType.of(void.class)));
}
```
I was going to quote [Jackson](https://github.com/FasterXML/jackson-databind/blob/2.15/src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java#L774) but the code is kind of dirty/complicated, however it works on the same principle. It also ensures that what comes after `get`/`is` corresponds to the name of a field.
