### ISSUE TITLE
FamixJavaClass>>isIgnored

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Famix#540]
What is this method? Where does it comes from? Why is it multivalued?

**Comment by ClotildeToullec** [comment]
It's only checking if a class is annotated with 'Ignore'. This happens only in tests.
No senders. According to its commits history, it's legacy.
I don't understand the `<multivalued>`

I vote for removal or at least deprecation

**Comment by badetitou** [comment]
It is present at some point in a VerveineJ export? 
if so, deprecation seems a better choice IMO

**Comment by ClotildeToullec** [comment]
It's derived, so not sure it's exported?

**Comment by NicolasAnquetil** [comment]
Answer to @badetitou :
No, not exported by VerveineJ, no idea what this can be
