### ISSUE TITLE
Famix-Java does not have references to extends element of TypeParameter

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#553]
FamixJava does not allow one to represent Method TypeParameter.
For instance

```java
void <T extends Hello> T aMethod() {
}
```

With the above code, a type `T` will be created, but we have no information about it. And no reference to the type `Hello` is created

**Comment by NicolasAnquetil** [comment]
seems related to #508 
We started reflection on this but it is not closed yet.
To be discussed in next Moose meeting

**Comment by anneetien** [comment]
fixed with the work on parameter #508
