### ISSUE TITLE
Should we remove declaredSourceLanguage slot ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#58]
On Inovelan model (roughly 1.2 G. memory size), there are > 1,000,000 SourcedEntity
Removing this slot would save 8 x 1,000,000 = 8 M (0,7% of total model memory)

With metamodels per language, maybe this slot is no longer needed ?

**Comment by anneetien** [comment]
Normally, now we know the MM so we can now the sourceLanguage, isn’t it?

**Comment by NicolasAnquetil** [comment]
Thinking about it, we still have the idea of having meta-models for multi-languages project
So the idea would be to keep the trait in FamixNG but not put it by default in all metamodels

**Comment by NicolasAnquetil** [comment]
see #177

**Comment by NicolasAnquetil** [comment]
So thinking about it:
1- I cannot remember a case where we needed to use this #declaredSourceLanguage. We (almost?) always have models on only one sourceLanguage and we know in this case what we are analyzing if only because of the language specific metamodel (FamixJava, PhamixSt, ...)
2- if we ever need to create a meta-models for a multi-languages project we can always add this slot to the entities that we will declare for this metamodel

So I propose to remove the slot from TSourcedEntity and to create a TWithSourceLanguage that one could use whenever s-he needs it

**Comment by NicolasAnquetil** [comment]
Actually the trait TWithSourceLanguage already exist so we just need to do #177
