### ISSUE TITLE
Adding same entity twice in many-to-many relation has inconsistent behavior

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#590]
If two entities are in a many-to-many relationship, and the same entity is added twice, it is added only once in the entity receiving the `add` message, but twice in the opposite entity (the one in argument of the `add` message).
The issue is that this behavior should be consistent: either allow multiple relationship occurrences or not.

## Recreate
Create a generator with two entities in a many-to-many relation:
```st
MyGenerator >> define [
	(builder newClassNamed: #Foo) *-* (builder newClassNamed: #Bar)
]
```
Add the same entity twice:
```st
foo := MyFoo new.
bar := MyBar new.
foo addBar: bar.
foo addBar: bar.
```
Observe inconsistent behavior:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/78592838/236410433-fa421f31-a7e6-41ec-bd6f-f7c466c585a1.png">
`bar` is only once in `foo`'s collection, but `foo` is twice in `bar`'s.

## Fix
**Option 1:** It is OK to have the same entities in a relation more than once.

**Option 2:** Entities cannot be in the same relationship multiple times, and this should be consistent.

Personally, I am working on the [Value metamodel](https://github.com/moosetechnology/Famix-Value), so the first option sounds more convenient to me right now. For example, it is useful to represent that the same value can be in the same collection multiple times.

**Comment by NicolasAnquetil** [comment]
**option 1** for me too.
It is not the same to say that method-A invokes method-B once or 10 times

**Comment by badetitou** [comment]
That's an interesting question. In my opinion, it is strange... 
In the case of Nicolas, you would create multiple FamixInvocations.

There is also a problem with the following code because of what you discovered.

```st
foo := MyGenFoo new.
bar := MyGenBar new.
foo addBar: bar.
foo addBar: bar.


foo bars size. "1"
bar foos size. "2"

foo bars remove: bar.

foo bars size. "0"
bar foos size. "1"

bar foos remove: foo "Error"

```

Even if `bar` has still a _foo_, i can not remove it because of the double set.
So, I believe the correct behavior would be **option 2**, even if option 1 seems interesting.

it is link to the one way relationship Vincent wanted to implement (I do not know the state of his work)

**Comment by ClotildeToullec** [comment]
I agree with Benoit.

I can't really think of a case where 
- we would add twice the same object
- the relations should not be reified into 2 distinct associations (with the same source and target).

In other words: why do you have twice the same object ? To know that you need more info and this information should be carried by an association. Thus you would have 2 distinct associations in each collection.

**Comment by Gabriel-Darbord** [comment]
Then sticking with option 2, it is a bug and shall be fixed!
I looked into it, and the process of adding an element is:
- `FMSlotMultivalueLink>>#add:`, which handles inverse first, then add to local
  - `FMMany>>#add:to:`
    - `FMRelationSlot>>addAssociationFrom:to:`
      - `FMSlotMultivalueLink>>#inverseAdd:`, which simply adds to the underlying collection
  - `FMSlotMultivalueLink>>#unsafeAdd:`, which checks first, then add if not present

The issue happens when `FMRelationSlot>>addAssociationFrom:to:` calls `FMSlotMultivalueLink>>#inverseAdd:`, which makes no checks.
Interestingly, this might have slipped into Moose from the Pharo implementation of relations, which uses sets.
A fix would be to either modify `inverseAdd:` so that it simply calls `unsafeAdd:`, or to remove the `inverseAdd:` method and use `unsafeAdd:` instead.
I would prefer removing "useless" methods, but maybe keeping the semantics is important.

**Comment by badetitou** [comment]
We should ensure that the modification will not impact (or as less as possible) the performance
https://github.com/moosetechnology/Fame/pull/53

**Comment by Gabriel-Darbord** [comment]
After discussing with @ClotildeToullec, we decided to remove `inverseAdd:` and to use `unsafeAdd:` instead, see moosetechnology/Fame#57.
@badetitou I checked the performances using the example you gave in your PR and they were unaffected.
