### ISSUE TITLE
FamixJavaAnnotationType can be implemented

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#594]
Please consider the following piece of code

```java
package ad_hoc.annotations;

import java.lang.annotation.*;

/**
 * Marks a method as getter. Used by clients to read properties of a class.
 * In the modeling community, they'd say that GetProperty is a meta-
 * description (ie an element of the meta-model layer) and that its clients
 * are model-driven. GetProperty can be used to meta-describe any object.
 *
 */

@Retention(RetentionPolicy.RUNTIME) 
@Target(ElementType.METHOD)
public @interface GetProperty {

	public String value();

	class SubAnnotation implements GetProperty {}
	
}

```

The class SubAnnotation _implements_ the annotationType `@GetProperty `.
Thus we should add that an annotation can be implemented as an Interface

**Comment by NicolasAnquetil** [comment]
or is it a new type: FamixAnnotationInterface ?

**Comment by badetitou** [comment]
I do not know. If I understand well
`public @interface GetProperty ` is the proper way to create an annotation

**Comment by NicolasAnquetil** [comment]
my mistake

**Comment by NicolasAnquetil** [comment]
The fact that Java uses the words `@interface` and `implements` seems to indicate that they consider annotations as similar to interfaces.
I am not sure why ?
And I am not sure we should follow the same path.
For example in Pharo annotations (pragmas) are more similar to methods ...

We must be able to represent annotations, we must be able to represent the fact that there are sub-annotations, but it does not mean they need to be considered as interfaces ...
What does it mean that a class implements an annotation by the way ? Is it a real class ?

**Comment by badetitou** [comment]
Yes, I agree that they should not be kind of TInterface.
I was asking for TImplementable. And still, I agree that maybe we should choose subinheritence, or something else :-)

**Comment by ISayarLu** [comment]
@badetitou: Java AnnotationType uses TImplementable. Is this issue still not resolved?
