### ISSUE TITLE
Reimplement data generation for 'generatePlantUMLModelWithout' of FamixMMUMLDocumentor 

### ISSUE THREAD

**Issue by lsafina** [moosetechnology/Famix#597]
Currently the logic of 'generatePlantUMLModelWithout' is the following: generate all entities, hide those provided as an argument.

E.g:
```
FamixMMUMLDocumentor new
 beWithStub;
 model: FASTFortranModel ;
 generatePlantUMLModelWithout: { MooseModel . FASTFortranStatement}
```
Will generate (among others entities) a statement, statement relations and then a command to hide it:
```
class Statement << (C,white) >> #FFFFFF {
  String label
}
...
ScopableEntity <|-- Statement
...
hide Statement
```

Instead it should completely avoid generating anything of this.

The problem with the current solution is that if there are many entities were chosen to be hidden, the place on the display are still being reserved for them, which makes a plot incredibly wide and hardly readable

**Comment by NicolasAnquetil** [comment]
Solved the problem by telling the exporter what classes we want instead of what classes we don't want.
Here all classes from FASTFortranModel without the ones having a name XYZStatement :
```St
regex := '[A-Z][a-zA-Z]*Statement' asRegex.
classes := (FASTFortranModel metamodel fmTypeOf: FASTFortranModel) package classes
 reject: [ :c | (c class = FM3Class) and: [ regex  matches: c name ] ].

FamixMMUMLDocumentor new 
 model: FASTFortranModel ;
 beWithStub ;
 generatePlantUMLWith: (classes collect: #implementingClass).
```
