### ISSUE TITLE
Access the collection of overriden methods

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#600]
There is a method named `isOverriden` that allows one to know if a method is overridden in a subclass.
It would be great to be able to know which are those methods.

**Comment by ClotildeToullec** [comment]
There is a branch for this issue.
Current status: 
- #overridingMethods is implemented but not tested yet
- #overridenMethod is not yet.

**Comment by ClotildeToullec** [comment]
Fixed by #613
