### ISSUE TITLE
Remove isStub from Associations

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#61]
Associations are very rarely stub (only known example: inheritance of Java classes)
from #55

**Comment by anneetien** [comment]
Why more an inheritance than a reference?
My question is: an association isStub when its target is stub? Or what does this mean that an inheritance is stub?

**Comment by NicolasAnquetil** [comment]
A stub is when we don't have the source code for it.

So an association is a stub when we can deduce it from something else than the source code.
This is the case for inheritance in java because we can ask a class what is it's superclass even if we don't have it's source code.

This is the only example of a stub association that I can see for now.

**Comment by NicolasAnquetil** [comment]
see #186
