### ISSUE TITLE
It's difficult to guess all relations of a class looking at its declaration

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#641]
Take a class like `FamixJavaException` try to guess all its relationship

Not simple: One can olook at its implementation, all "accessing" methods
- ignore the ones that are not introducing a relationship (eg. the one from TEntityMetaLevelDependency)
- ignore the "redundant" ones (eg a multi relationship can have several methods: getter/setter, addXYZ:, numberOfXYZ
- you may have to look to the superclasses

One can look at the UML, but  they can be very big

One can look at the generator, but some traits define relationships, other don't

...

Not sure this is something we want to act upon, but it hit me several times and I did not find an easy solution

**Comment by badetitou** [comment]
If you mean. In the Calypso browser. Why not add a tab with the relations at 1 level ? Like that you would have a convenient way to see all the direct relations?

**Comment by badetitou** [comment]
If you mean. In the Calypso browser. Why not add a tab with the relations at 1 level ? Like that you would have a convenient way to see all the direct relations?

We can even add the moose properties in the uml. But I'm afraid they are too much properties sometimes

**Comment by Gabriel-Darbord** [comment]
Could exporting relations in class comment (#126) help?
