### ISSUE TITLE
`FamixJavaMethod>>#isSetter` difficulties

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#678]
Here is the current definition of `isSetter`:
```st
^ self kind = #setter or: [
  self name isNotNil and: [
  (self name beginsWith: 'set') and: [
  self parameters size = 1 and: [
  self declaredType isNotNil and: [
  self declaredType name = 'void' and: [
  self outgoingInvocations isEmpty ] ] ] ] ] ]
```
However here is a setter I came across that fails this check because of an outgoing invocation:
```java
public void setRoles(final String[] roles) {
    this.roles = Arrays.copyOf(roles, roles.length);
}
```
I think the current definition of `isSetter` may be too strict, and we could remove the check on outgoing invocations.
Also, why not set the kind to `#setter` if all conditions are true, to avoid doing all the checks more than once?

**Comment by badetitou** [comment]
The isSetter and isGetter methods try to check that the method does not perform any computations like when developing a Java Pojo. 
This was useful when searching for a method that follows Pojo convention by name but not by code. It was part of the thesis of Nour.

**Comment by Gabriel-Darbord** [comment]
It was changed once before in #532, so it could be changed again.
With Famix, we should be strict enough to avoid false positives, but we could also be lax enough to accept some unusual cases like this.
I think if we really want to know for sure if it is a setter, we need FAST to do a thorough analysis.
