### ISSUE TITLE
Redondancy of TMethod>>#isAbstract

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#69]
Until Moose 8, methods had a #isAbstract property stored in the modifiers. 

During one of Anne's refactoring (599bc1b4071436bb4a86b74186e0d00f2bc210fb), the property #isAbstract was added to TMethod directly, but the property is still on THasModifiers. 

This causes troubles because the two ways are clashing and need to be taken care of in each generators with methods.

Since the team detected memory problems, I would opt to remove the version on TMethod that takes more memory and keep the version on THasModifiers.

**Comment by anneetien** [comment]
We chose the opposite:
- keeping isAbstract in TMethod 
- removing it from THasModifier 
Indeed, abstract IS NOT a modifier. So the semantic is more important than memory.

**Comment by ClotildeToullec** [comment]
Fixed by a88ab212ddc54e8b18fcf4d06c6bb1498bf18c83
