### ISSUE TITLE
Rename relationship between `TParametricEntity` and `TConcretisation`

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#706]
Each ParametricEntity can be related to another one by a Concretisation association, where one is more generic and the other is more concrete.
The name of the relation of the more generic entity to the association is `concretisation`, which is fitting.
However, the name of the opposite relation is `genericEntity`, which I think is misleading.
Especially since the relation from the association to the more generic entity is already called `genericEntity`, where it makes sense.
This would lead to code as follows:
```st
parametricEntity genericEntity "<- Concretisation" genericEntity "<- ParametricEntity"
```

I suggest to rename the opposite relation of `concretisation`, from `genericEntity` to `genericization` (a real word).
```st
concreteEntity genericization "<- Concretisation" genericEntity "<- ParametricEntity"
```

**Comment by NicolasAnquetil** [comment]
I am not sure `genericEntity` is a good name for the relation because it is not really an Entity
May be this is the one we should rename (or may be both)

**Comment by Gabriel-Darbord** [comment]
This is what I meant but the wording of "opposite relation" was poorly chosen.
I'm referring to the opposite of `concreteEntity`, which is called `genericEntitities` in the diagram, and `genericEntity` in the current implementation.
<img width="139" alt="image" src="https://github.com/moosetechnology/Famix/assets/78592838/9d55eb45-f8d2-453b-9f92-e3238a36a68a">

The renaming allows us to write instead of the previous example:
```st
concreteEntity genericization "<- Concretisation" genericEntity "<- ParametricEntity"
```
