### ISSUE TITLE
Rename `FamixTParametricEntity >> rootGenericEntity` as `genericEntity`

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#707]
The `rootGenericEntity` method was added with the misconception that concretizations form a recursive tree structure.
In practice, every ParametricEntity except the root generic entity is a leaf, so the tree has a depth of at most one.
So the current implementation, which does an iteration, and the name `rootGenericEntity` make little sense.
I would like to just call it `genericEntity`, but there is currently a relation with that name so this change depends on #706.
This method always returns the generic entity, which usually contains the relevant information, such as the source anchor.
```st
genericEntity

	^ self genericization
		  ifNil: [ self ]
		  ifNotNil: [ :concretization | concretization genericEntity ]
```

**Comment by NicolasAnquetil** [comment]
May be I misunderstood the issue, but concretization **can b**e a tree (even if it is rare):

If you have a generic with 2 type parameters (like `Map<K,V>`), then you can have a partial concretization where you specify only type (ex: `MapStrings<V> extends MAP<String,V>`), and then a complete concretization of this one.

**Comment by Gabriel-Darbord** [comment]
In the scenario you describe, there is an inheritance relationship between two concretizations:
![image](https://github.com/moosetechnology/Famix/assets/78592838/7ff61754-7cb9-431d-8968-b46b9c338efb)

A concretization tree always has a height of at most two, because an entity that is concrete can never also be generic in another concretization relation.
The following never happens:
![image](https://github.com/moosetechnology/Famix/assets/78592838/4fef11cd-b4fd-41c6-8869-72915fa892b9)

There is always a single generic entity, and possibly multiple concrete entities:
![image](https://github.com/moosetechnology/Famix/assets/78592838/4a3f0bd6-be7e-4bfb-9c1b-1e707f0943de)

The `genericEntity` method will always return the generic entity in a concretization relationship.
