### ISSUE TITLE
Change FamixJavaEntity comment

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#709]
Currently, [FamixJavaEntity has the following comment](https://github.com/moosetechnology/Famix/blob/development/src/Famix-Java-Entities/FamixJavaEntity.class.st#L1-L12) in plain text (without code block):
```
file := 'ArgoUML-0-34.mse' asFileReference readStream.

repo := MooseModel importFrom: file withMetamodel: FamixJavaModel metamodel.

model := MooseModel new.
model silentlyAddAll: repo elements.
model entityStorage forRuntime.
model
```
Is this still relevant?
It probably needs an update, and an explanation in the comment about what the code does.

**Comment by jecisc** [comment]
The line about entity sotrage is out of date anyway.

I think we can remove it
