### ISSUE TITLE
Should file importers be in MooseIDE ?

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#728]
Currently the MSE and JSON file importers are in MooseIDE. I am wondering if it would not make sense for them to be in Famix instead since they are more models entities than view entities?

**Comment by NicolasAnquetil** [comment]
makes sense to me
we had a discussion on this with @fuhrmanator recently

**Comment by jecisc** [comment]
For information, I also moved some behavior to detect the right model for an importer and a file to import from the presenters to the importers. Like this I can reuse it for the Software Heritage importer and this can help other people I guess
