### ISSUE TITLE
Rework #numberOfComments?

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#735]
I found the method #numberOfComments and there are two points I would like to rework on it.

The first one is that this methods has a cache even if it is really fast and a setter to bypass the compute block of the cache.
I think this was done in order to be able to set the number of comments even if we do not have the comments in the model.
But I think that no parser currently working with Moose uses this feature. I would vote to simplify this and remove the setter and cache.

The second thing is that this method is reimplemented on JavaClass, StClass, JavaMethod and StMethod. For the methods the change is useless and I'll remove those. But for the classes, the behavior change and it also counts the comments of all the children. 

To me it is bad to have one entity behaving in a different way than the other. After discussing with Benoit I think we should always return the number of comments of the entity without considering the children in #numberOfComments. 

Does this seems good? @ClotildeToullec @NicolasAnquetil @anneetien ?

**Comment by NicolasAnquetil** [comment]
I would say no to 1st point and yes to 2nd.

For the frsit point:
- Having a setter for a property is not  big additional complexity and as a general rule
- It is handy to be able to set any metrics instead of computing it.
- numberOfComments is a metrics so let's have it behave like any other one

**Comment by jecisc** [comment]
I don't have any strong opinion on what to do about it so it's fine for me to let it
