### ISSUE TITLE
asOrderedCollection can't be used correctly for getting targets 

### ISSUE THREAD

**Issue by MohamedCooding** [moosetechnology/Famix#768]
In FamixTAssociation, the allTargets method return a Collection of collection [...] of Collection instead of returning one simple collection containing the targets. 
The current implementation uses the deprecated message "asOrderedCollection".

**Comment by uNouss** [comment]
This commit 8c7cc683ac5be1733421bba0dce266dbfe3d5661 resolve this issue.
