### ISSUE TITLE
FamixTFunction should use FamixTInvocable

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#816]
At least I think so?
In my opinion, this is the trait that makes the most sense to represent both methods and functions.

As a side note, other traits that exclusively represent both, at least when considering only the Famix metamodels, are FamixTWithStatements, FamixTWithLocalVariables and FamixTWithParameters.

**Comment by NicolasAnquetil** [comment]
right ... and it does  (well in my image at least)
```st
Trait << #FamixTFunction
	traits: {FamixTHasSignature + FamixTInvocable + FamixTNamedEntity + FamixTTypedEntity + FamixTWithLocalVariables + FamixTWithParameters + FamixTWithStatements + TEntityMetaLevelDependency};
	slots: { #functionOwner => FMOne type: #FamixTWithFunctions opposite: #functions };
	tag: 'Behavioral';
	package: 'Famix-Traits'
```

**Comment by Gabriel-Darbord** [comment]
Ah indeed I see it in a new image, my bad.
