### ISSUE TITLE
Remove private state to save memory

### ISSUE THREAD

**Issue by jecisc** [moosetechnology/Famix#82]
In the past, we had multiple kinds of private states. But now we only have one. 

Private states take a lot of memory since they are created with each entity, association, group, source anchor, ...

Since it now consists of 2 collections and their management, I think it would be wise to inline this behaviour and state directly in MooseObject. Like this, we would save 1 object by moose object. 

The method MooseObject>>#privateState can be deprecated and rewritten to return self. 

We need to be careful because we need to rename the attribute "attributes" before to avoid a name clash with FamixTType>>attributes.

**Comment by badetitou** [comment]
So everything still exist but in MooseObject ?

**Comment by badetitou** [comment]
Can we keep the private state classes and deprecated them?

**Comment by jecisc** [comment]
Yes!
