### ISSUE TITLE
Famix-extensions methods which are not real properties

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#826]
In FamixJava and FamixSmalltalk, some accessing methods are implemented manually.
exemple:
```st
FamixJavaMethod >> invokedMethods
	<FMProperty: #invokedMethods type: #FamixJavaMethod> <derived> <multivalued>
	<FMComment: 'The methods invoked by the receiver'>
	
	^ self invokedBehaviours select: [ :each | each isMethod ]
```
```st
- FamixStMethod >> invokedMethods
	<FMProperty: #invokedMethods type: #FamixStMethod> <derived> <multivalued>
	<FMComment: 'The methods invoked by the receiver'>
	
	^ self invokedBehaviours select: [ :each | each isMethod ]
```

They can be found in the Famix-Extensions category

They are met-described, so they appear in `mooseDescription allProperties`
But the setter method is not implemented, so they are actually "half Famix properties"

So either they should not be meta-described, or the corresponding setters should be created

**Comment by badetitou** [comment]
These properties have the `derived` pragma. So it is expected that they do not have specific setter? Do you feel they created bugs? Is there any reason you want to have setter? Or maybe it's only because you want to separate derived and not derived properties?

**Comment by badetitou** [comment]
Ahh indeed! 
Derived is also used by model exporter. To not export each side of the relation 
I agree to find another way to express this relations. Maybe `<computer property>`

However. I think it is important to keep them describe in the metamodel

**Comment by badetitou** [comment]
I was thinking about `computed properties` but my phone miss fixed it. 
Query property seems nice to me too

**Comment by NicolasAnquetil** [comment]
Actually there is a `<generated>` pragma that the generator puts in the "normal" properties.
I am now thinking that we can just filter out those that are not generated...

In this case there would be nothing to do !
