### ISSUE TITLE
#opposites and #atScope: return result asSet which is not always what one wants

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#89]
For example to compute the weight of dependencies between two packages, one wants to know all the links there are and asSet can withdraw some

**Comment by NicolasAnquetil** [comment]
May be asSet can be explicitly added into the MooseQuery DSL and removed from implementatin of #opposites , #atScope: ?

**Comment by jecisc** [comment]
What you want is already possible with the DSL.

`(self query ancestors result: OrderedCollection new) ofType: FamixTMethod`

or via the query object:

```st
MQScopeQuery new
	receiver: receiver;
	result: OrderedCollection new;
	direction: MQScopeUpStrategy;
	typeStrategy:  MQScopeTypeStrategy scope: aFamixType;
	execute
```

The set is the default option because it is the most common thing we want and for performance reasons.
