### ISSUE TITLE
TMethod should not define all these slots 

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#96]
isAbstract, isClassSide, kind should be abstracted in specific simple (core) traits and TMethod would only have a slot: parentType -> TWithMethods

**Comment by ClotildeToullec** [comment]
isAbstract has been removed in https://github.com/moosetechnology/Famix/pull/195

**Comment by ClotildeToullec** [comment]
The only remaining slot (apart from #parentType) is #kind.

If we want to extract it to a trait, this is still to be done. Maybe with helper methods 
(`beConstructor`, `beConstant`, `beGetter`, `beSetter`) to avoid the use of symbols everywhere and to remove the possibility to do `aMethod kind: #aTotallyIrrelevantKind`.
If not, we can close this issue.
